// AUTH
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const LOGOUT = 'LOGOUT';

// ITEMS
export const GET_SINGLE_ITEM = 'GET_SINGLE_ITEM';
export const SET_SINGLE_ITEM = 'SET_SINGLE_ITEM';
export const UPDATE_SINGLE_ITEM = 'UPDATE_SINGLE_ITEM';
export const LOADING_SINGLE_ITEM = 'LOADING_SINGLE_ITEM';
export const SET_ALL_ITEMS = 'SET_ALL_ITEMS';
export const LOADING_ALL_ITEMS = 'LOADING_ALL_ITEMS';
export const RELOAD_ITEMS = 'RELOAD_ITEMS';

// BOOKS
export const GET_SINGLE_BOOK = 'GET_SINGLE_BOOK';
export const SET_SINGLE_BOOK = 'SET_SINGLE_BOOK';
export const UPDATE_SINGLE_BOOK = 'UPDATE_SINGLE_BOOK';
export const BORROW_SINGLE_BOOK = 'BORROW_SINGLE_BOOK';
export const RETURN_SINGLE_BOOK = 'RETURN_SINGLE_BOOK';
export const LOADING_SINGLE_BOOK = 'LOADING_SINGLE_BOOK';
export const SET_ALL_BOOKS = 'SET_ALL_BOOKS';
export const LOADING_ALL_BOOKS = 'LOADING_ALL_BOOKS';
export const RELOAD_BOOKS = 'RELOAD_BOOKS';
export const SET_ALL_AVAILABLE = 'SET_ALL_AVAILABLE';
export const LOADING_ALL_AVAILABLE = 'LOADING_ALL_AVAILABLE';
export const RELOAD_AVAILABLE = 'RELOAD_AVAILABLE';

// USERS
export const UPDATING_USER_INFO = 'UPDATING_USER_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
